// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmDe2C8wVw5F1akDbFSFzNSBy81_KnHDg',
    appId: '1:492492144231:web:f44e4a2d4daf60a67b9ec2',
    messagingSenderId: '492492144231',
    projectId: 'notesapp-eb1d3',
    authDomain: 'notesapp-eb1d3.firebaseapp.com',
    storageBucket: 'notesapp-eb1d3.appspot.com',
    measurementId: 'G-ZJNNYYREBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1XbNwoaZ_RO3b4js_G4XFMFk_6SDLVR8',
    appId: '1:492492144231:android:af3021bb87f49cfa7b9ec2',
    messagingSenderId: '492492144231',
    projectId: 'notesapp-eb1d3',
    storageBucket: 'notesapp-eb1d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMeGJXOWLc8vPH8-tLalvcqOI6Lqmbk6s',
    appId: '1:492492144231:ios:b5c08e5517f92b827b9ec2',
    messagingSenderId: '492492144231',
    projectId: 'notesapp-eb1d3',
    storageBucket: 'notesapp-eb1d3.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMeGJXOWLc8vPH8-tLalvcqOI6Lqmbk6s',
    appId: '1:492492144231:ios:304e4f70671c05787b9ec2',
    messagingSenderId: '492492144231',
    projectId: 'notesapp-eb1d3',
    storageBucket: 'notesapp-eb1d3.appspot.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
